name: Java CI with Maven

on: [push, pull_request]

jobs:
  bulid:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Bulid with Maven
      run: mvn -B -e verify
